# =============== top level gatus ks ===============
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - deployment.yaml
  - service.yaml
  - config.yaml
  - sa.yaml
  - namespace.yaml

commonLabels:
  app.kubernetes.io/name: gatus
