apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-values
  namespace: default
data:
  values: |
    USER-SUPPLIED VALUES:
    controller:
      autoscaling:
        enabled: true
        maxReplicas: 5
        minReplicas: 1
        targetCPUUtilizationPercentage: 50
        targetMemoryUtilizationPercentage: 100
      config:
        use-forwarded-headers: "true"
      ingressClassResource:
        default: false
      
      resources:
        requests:
          cpu: 50m
          memory: 128Mi